# Generated by Django 3.0.1 on 2020-06-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourcvMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedRecordTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('publication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourcvMS.PublicationType')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourcvMS.ImportedRecordType')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourcvMS.ImportedSource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedRecordTemplateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('publication_field', models.CharField(blank=True, max_length=100, null=True)),
                ('record_field', models.CharField(blank=True, max_length=100, null=True)),
                ('transform', models.CharField(blank=True, max_length=200, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourcvMS.ImportedRecordTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
