# Generated by Django 3.0.1 on 2020-06-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourcvMS', '0003_auto_20200624_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedrecordtemplate',
            name='process_journal',
            field=models.BooleanField(default=False),
        ),
    ]
