# Generated by Django 3.0.1 on 2020-06-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourcvMS', '0005_auto_20200628_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='book_title',
            new_name='booktitle',
        ),
    ]
