# Generated by Django 3.0.1 on 2020-07-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourcvMS', '0006_auto_20200629_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('factor_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'journal', 'booktitle', 'title']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='JournalYearRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('centil_average', models.IntegerField()),
                ('rank_average', models.IntegerField()),
                ('number_of_journals', models.IntegerField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourcvMS.Journal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalSourceYearRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('centil_average', models.IntegerField()),
                ('rank_average', models.IntegerField()),
                ('number_of_journals', models.IntegerField()),
                ('factor', models.FloatField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourcvMS.Journal')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourcvMS.JournalYearRank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalSourceYearCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('centil', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('number_of_journals', models.IntegerField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourcvMS.Journal')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourcvMS.JournalYearRank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
