# Generated by Django 3.0.1 on 2020-08-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourcvMS', '0007_auto_20200725_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalsourceyearcategory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
