# Generated by Django 3.0.1 on 2020-08-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourcvMS', '0008_journalsourceyearcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsourceyearcategory',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourcvMS.RankingSource'),
        ),
        migrations.AlterField(
            model_name='journalsourceyearrank',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourcvMS.RankingSource'),
        ),
    ]
