# Generated by Django 3.0.1 on 2020-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourcvMS', '0012_publicationtype_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtype',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
